//*****************************************************************************
//
//      This code was generated by the JADE Exposure Wizard.
//
//      JADE Version    : 20.0.01
//      Generation date : Tuesday, 19 January 2021
//      Generated by    : cnwta3
//      JADE Schema     : JoobSpatialDemoSchema
//      Exposure Name   : SpatialDemoExposure
//
//      NOTE: You should NOT change this file as it may cause incorrect
//            behaviour. Any changes that you do make will be lost if
//            this code is regenerated.
//
//*****************************************************************************

namespace SpatialDemoExposure
{
	using System;
	using System.Collections.Generic;
	using System.Runtime.Serialization;
	using JadeSoftware.Joob;
	using JadeSoftware.Joob.Client;
	using JadeSoftware.Joob.Metadata;
	using JadeSoftware.Joob.Management;
	using JadeSoftware.Joob.MetaSchema;
	using JadeSoftware.Jade.DotNetInterop;


	[System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
	[JadeSoftware.Joob.Client.JoobDictionaryKeyClassAttribute(typeof(CityByNameDict))]
	public partial class CityByNameDictKey : JadeSoftware.Joob.JoobDictionaryKey
	{

		private static JadeSoftware.Joob.KeyMetadata _name = MetadataCache<CityByNameDictMetadata>.GetData(null).NameKey;

		public CityByNameDictKey() :
			base(new JadeSoftware.Joob.KeyMetadata[] {
					_name})
		{
		}

		public CityByNameDictKey(String name) :
				this()
		{
			this.Name = name;
		}

		[JadeSoftware.Joob.Client.JoobDictionaryKeyAttribute("name", 0, typeof(String), Length = 50, CaseSensitive = true, Ascending = true, SortOrder = 0)]
		public String Name
		{
			get
			{
				return ((String)(this.Keys[0]));
			}
			set
			{
				this.Keys[0] = value;
			}
		}
	}

	[System.Runtime.Serialization.KnownTypeAttribute(typeof(City))]
	[System.Runtime.Serialization.KnownTypeAttribute(typeof(CityByNameDictKey))]
	[System.Runtime.Serialization.CollectionDataContractAttribute(IsReference=true)]
	[System.ComponentModel.DataAnnotations.MetadataTypeAttribute(typeof(CityByNameDictMetadata))]
	[JadeSoftware.Joob.Client.JoobClassAttribute("CityByNameDict", "RootSchema.JoobSpatialDemoSchema", ClassNamespace = "SpatialDemoExposure", DuplicatesAllowed = true)]
	[JadeSoftware.Joob.Metadata.JomlTypeAttribute(JadeSoftware.Joob.Metadata.JomlTypeKind.ClassCollection, "CityByNameDict", typeof(MemberKeyDictionary<CityByNameDictKey, City>), MembershipType=typeof(City), Keys="name")]
	public partial class CityByNameDict : MemberKeyDictionary<CityByNameDictKey, City>
	{

		private static CityByNameDictMetadata _metaModel;

		partial void Initialize();


		static CityByNameDict()
		{
			_metaModel = MetadataCache<CityByNameDictMetadata>.GetData(null);
		}

		public CityByNameDict() : 
				this(JadeSoftware.Joob.ClassPersistence.Persistent)
		{
		}

		public CityByNameDict(JadeSoftware.Joob.ClassPersistence lifetime) : 
				base(lifetime, typeof(CityByNameDict), _metaModel.metaClass)
		{
			this.Initialize();
		}

		protected CityByNameDict(JadeSoftware.Joob.ClassPersistence lifetime, System.Type type, JadeSoftware.Joob.ClassMetadata metaClass) :
		        base(lifetime, type, metaClass)
		{
		    this.Initialize();
		}

		public virtual City this[String name]
		{
			get
			{
				CityByNameDictKey _key_ = new CityByNameDictKey(name);
				 return base[_key_];
			}
			set
			{
				CityByNameDictKey _key_ = new CityByNameDictKey(name);
				base[_key_] = value;
			}
		}

		public virtual bool TryGetValue(String name, out City value)
		{
			CityByNameDictKey _key_ = new CityByNameDictKey(name);
			return base.TryGetValue(_key_, out value);
		}

		public virtual bool TryGetValue(String name, JadeSoftware.Joob.SearchStrategy strategy, out City value)
		{
			CityByNameDictKey _key_ = new CityByNameDictKey(name);
			return base.TryGetValue(_key_, strategy, out value);
		}

		public virtual IJoobDictionaryEnumerable<CityByNameDictKey, City> StartingAtKey(String name)
		{
			CityByNameDictKey _key_ = new CityByNameDictKey(name);
			return base.StartingAtKey(_key_);
		}

		public virtual IJoobDictionaryEnumerable<CityByNameDictKey, City> StartingAtKey(String name, JadeSoftware.Joob.SearchStrategy strategy)
		{
			CityByNameDictKey _key_ = new CityByNameDictKey(name);
			return base.StartingAtKey(_key_, strategy);
		}

		public virtual void PutAtKey(String name, City value)
		{
			CityByNameDictKey _key_ = new CityByNameDictKey(name);
			base.PutAtKey(_key_, value);
		}

		public virtual bool TryPutAtKey(String name, City value)
		{
			CityByNameDictKey _key_ = new CityByNameDictKey(name);
			return base.TryPutAtKey(_key_, value);
		}

		public virtual bool TryPutAtKeyDeferred(String name, City value)
		{
			CityByNameDictKey _key_ = new CityByNameDictKey(name);
			return base.TryPutAtKeyDeferred(_key_, value);
		}

		public virtual void Remove(String name)
		{
			CityByNameDictKey _key_ = new CityByNameDictKey(name);
			base.Remove(_key_);
		}

		public virtual void Remove(String name, City member)
		{
			CityByNameDictKey _key_ = new CityByNameDictKey(name);
			base.Remove(_key_, member);
		}

		public virtual City TryRemove(String name)
		{
			CityByNameDictKey _key_ = new CityByNameDictKey(name);
			return base.TryRemove(_key_);
		}

		public virtual bool TryRemove(String name, City member)
		{
			CityByNameDictKey _key_ = new CityByNameDictKey(name);
			return base.TryRemove(_key_, member);
		}

		public virtual bool TryRemoveDeferred(String name, City member)
		{
			CityByNameDictKey _key_ = new CityByNameDictKey(name);
			return base.TryRemoveDeferred(_key_, member);
		}

		public virtual bool ContainsKey(String name)
		{
			CityByNameDictKey _key_ = new CityByNameDictKey(name);
			return base.ContainsKey(_key_);
		}
	}

	[System.Runtime.Serialization.KnownTypeAttribute(typeof(City))]
	[System.Runtime.Serialization.KnownTypeAttribute(typeof(CityByNameDictKey))]
	[System.Runtime.Serialization.CollectionDataContractAttribute(IsReference=true)]
	[System.ComponentModel.DataAnnotations.MetadataTypeAttribute(typeof(CityByNameDictMetadata))]
	[JadeSoftware.Joob.Client.JoobClassAttribute("CityByNameDict", "RootSchema.JoobSpatialDemoSchema", ClassNamespace="SpatialDemoExposure")]
	public abstract partial class CityByNameDict<TKey, TValue> : MemberKeyDictionary<TKey, TValue>
		where TKey : JadeSoftware.Joob.IJoobDictionaryKey, new ()
		where TValue : City
	{

		private static CityByNameDictMetadata _metaModel;

		partial void Initialize();


		static CityByNameDict()
		{
			_metaModel = MetadataCache<CityByNameDictMetadata>.GetData(null);
		}

		protected CityByNameDict(JadeSoftware.Joob.ClassPersistence lifetime, System.Type type, JadeSoftware.Joob.ClassMetadata metaClass) :
		        base(lifetime, type, metaClass)
		{
		    this.Initialize();
		}
	}

	public partial class CityByNameDictMetadata : JadeSoftware.Joob.IDomainMetadata
	{

		internal JadeSoftware.Joob.ClassMetadata metaClass;

		internal JadeSoftware.Joob.KeyMetadata NameKey;

		private CityByNameDictMetadata()
		{
		}

		public CityByNameDictMetadata(JadeSoftware.Joob.Client.JoobConnection connection)
		{
			this.InitializeProperties(connection);
		}

		private void InitializeProperties(JadeSoftware.Joob.Client.JoobConnection connection)
		{
			metaClass = new JadeSoftware.Joob.ClassMetadata(connection, typeof(CityByNameDict), "CityByNameDict", "RootSchema.JoobSpatialDemoSchema", JadeSoftware.Joob.DuplicationOption.Allowed);
			this.NameKey = metaClass.CheckMemberKey(typeof(CityByNameDict), typeof(City), "name", typeof(String), 50, JadeSoftware.Joob.CaseSensitivityOption.Sensitive, JadeSoftware.Joob.KeyOrderOption.Ascending);
		}
	}
}
