//*****************************************************************************
//
//      This code was generated by the JADE Exposure Wizard.
//
//      JADE Version    : 20.0.01
//      Generation date : Monday, 18 January 2021
//      Generated by    : cnwta3
//      JADE Schema     : JoobSpatialDemoSchema
//      Exposure Name   : SpatialDemoExposure
//
//      NOTE: You should NOT change this file as it may cause incorrect
//            behaviour. Any changes that you do make will be lost if
//            this code is regenerated.
//
//*****************************************************************************

namespace SpatialDemoExposure
{
	using System;
	using System.Collections.Generic;
	using System.Runtime.Serialization;
	using JadeSoftware.Joob;
	using JadeSoftware.Joob.Client;
	using JadeSoftware.Joob.Metadata;
	using JadeSoftware.Joob.Management;
	using JadeSoftware.Joob.MetaSchema;
	using JadeSoftware.Jade.DotNetInterop;


	[System.Runtime.Serialization.KnownTypeAttribute(typeof(JoobGeometry))]
	[System.Runtime.Serialization.KnownTypeAttribute(typeof(City))]
	[System.Runtime.Serialization.CollectionDataContractAttribute(IsReference=true)]
	[System.ComponentModel.DataAnnotations.MetadataTypeAttribute(typeof(CityByGeomRTreeMetadata))]
	[JadeSoftware.Joob.Client.JoobClassAttribute("CityByGeomRTree", "RootSchema.JoobSpatialDemoSchema", ClassNamespace = "SpatialDemoExposure", DuplicatesAllowed = false)]
	[JadeSoftware.Joob.Metadata.JomlTypeAttribute(JadeSoftware.Joob.Metadata.JomlTypeKind.ClassCollection, "CityByGeomRTree", typeof(MemberKeyRTree<JoobGeometry, City>), MembershipType=typeof(City), Keys="geom")]
	public partial class CityByGeomRTree : MemberKeyRTree<JoobGeometry, City>
	{

		private static CityByGeomRTreeMetadata _metaModel;

		partial void Initialize();


		static CityByGeomRTree()
		{
			_metaModel = MetadataCache<CityByGeomRTreeMetadata>.GetData(null);
		}

		public CityByGeomRTree() : 
				this(JadeSoftware.Joob.ClassPersistence.Persistent)
		{
		}

		public CityByGeomRTree(JadeSoftware.Joob.ClassPersistence lifetime) : 
				base(lifetime, typeof(CityByGeomRTree), _metaModel.metaClass)
		{
			this.Initialize();
		}

		protected CityByGeomRTree(JadeSoftware.Joob.ClassPersistence lifetime, System.Type type, JadeSoftware.Joob.ClassMetadata metaClass) :
		        base(lifetime, type, metaClass)
		{
		    this.Initialize();
		}
	}

	public partial class CityByGeomRTreeMetadata : JadeSoftware.Joob.IDomainMetadata
	{

		internal JadeSoftware.Joob.ClassMetadata metaClass;

		internal JadeSoftware.Joob.KeyMetadata GeomKey;

		private CityByGeomRTreeMetadata()
		{
		}

		public CityByGeomRTreeMetadata(JadeSoftware.Joob.Client.JoobConnection connection)
		{
			this.InitializeProperties(connection);
		}

		private void InitializeProperties(JadeSoftware.Joob.Client.JoobConnection connection)
		{
			MetadataCache<JoobGeometryMetadata>.LoadData(null);
			metaClass = new JadeSoftware.Joob.ClassMetadata(connection, typeof(CityByGeomRTree), "CityByGeomRTree", "RootSchema.JoobSpatialDemoSchema", JadeSoftware.Joob.DuplicationOption.NotAllowed);
			this.GeomKey = metaClass.CheckMemberKey(typeof(CityByGeomRTree), typeof(City), "geom", typeof(JoobGeometry), JadeSoftware.Joob.CaseSensitivityOption.Sensitive, JadeSoftware.Joob.KeyOrderOption.Ascending);
		}
	}
}
