//*****************************************************************************
//
//      This code was generated by the JADE Exposure Wizard.
//
//      JADE Version    : 20.0.01
//      Generation date : Tuesday, 19 January 2021
//      Generated by    : cnwta3
//      JADE Schema     : JoobSpatialDemoSchema
//      Exposure Name   : SpatialDemoExposure
//
//      NOTE: You should NOT change this file as it may cause incorrect
//            behaviour. Any changes that you do make will be lost if
//            this code is regenerated.
//
//*****************************************************************************

namespace SpatialDemoExposure
{
	using System;
	using System.Collections.Generic;
	using System.Runtime.Serialization;
	using JadeSoftware.Joob;
	using JadeSoftware.Joob.Client;
	using JadeSoftware.Joob.Metadata;
	using JadeSoftware.Joob.Management;
	using JadeSoftware.Joob.MetaSchema;
	using JadeSoftware.Jade.DotNetInterop;


	[System.Runtime.Serialization.KnownTypeAttribute(typeof(JoobGeometry))]
	[System.Runtime.Serialization.KnownTypeAttribute(typeof(County))]
	[System.Runtime.Serialization.CollectionDataContractAttribute(IsReference=true)]
	[System.ComponentModel.DataAnnotations.MetadataTypeAttribute(typeof(CountyByGeomRTreeMetadata))]
	[JadeSoftware.Joob.Client.JoobClassAttribute("CountyByGeomRTree", "RootSchema.JoobSpatialDemoSchema", ClassNamespace = "SpatialDemoExposure", DuplicatesAllowed = false)]
	[JadeSoftware.Joob.Metadata.JomlTypeAttribute(JadeSoftware.Joob.Metadata.JomlTypeKind.ClassCollection, "CountyByGeomRTree", typeof(MemberKeyRTree<JoobGeometry, County>), MembershipType=typeof(County), Keys="geom")]
	public partial class CountyByGeomRTree : MemberKeyRTree<JoobGeometry, County>
	{

		private static CountyByGeomRTreeMetadata _metaModel;

		partial void Initialize();


		static CountyByGeomRTree()
		{
			_metaModel = MetadataCache<CountyByGeomRTreeMetadata>.GetData(null);
		}

		public CountyByGeomRTree() : 
				this(JadeSoftware.Joob.ClassPersistence.Persistent)
		{
		}

		public CountyByGeomRTree(JadeSoftware.Joob.ClassPersistence lifetime) : 
				base(lifetime, typeof(CountyByGeomRTree), _metaModel.metaClass)
		{
			this.Initialize();
		}

		protected CountyByGeomRTree(JadeSoftware.Joob.ClassPersistence lifetime, System.Type type, JadeSoftware.Joob.ClassMetadata metaClass) :
		        base(lifetime, type, metaClass)
		{
		    this.Initialize();
		}
	}

	public partial class CountyByGeomRTreeMetadata : JadeSoftware.Joob.IDomainMetadata
	{

		internal JadeSoftware.Joob.ClassMetadata metaClass;

		internal JadeSoftware.Joob.KeyMetadata GeomKey;

		private CountyByGeomRTreeMetadata()
		{
		}

		public CountyByGeomRTreeMetadata(JadeSoftware.Joob.Client.JoobConnection connection)
		{
			this.InitializeProperties(connection);
		}

		private void InitializeProperties(JadeSoftware.Joob.Client.JoobConnection connection)
		{
			MetadataCache<JoobGeometryMetadata>.LoadData(null);
			metaClass = new JadeSoftware.Joob.ClassMetadata(connection, typeof(CountyByGeomRTree), "CountyByGeomRTree", "RootSchema.JoobSpatialDemoSchema", JadeSoftware.Joob.DuplicationOption.NotAllowed);
			this.GeomKey = metaClass.CheckMemberKey(typeof(CountyByGeomRTree), typeof(County), "geom", typeof(JoobGeometry), JadeSoftware.Joob.CaseSensitivityOption.Sensitive, JadeSoftware.Joob.KeyOrderOption.Ascending);
		}
	}
}
