//*****************************************************************************
//
//      This code was generated by the JADE Exposure Wizard.
//
//      JADE Version    : 20.0.01
//      Generation date : Monday, 18 January 2021
//      Generated by    : cnwta3
//      JADE Schema     : JoobSpatialDemoSchema
//      Exposure Name   : SpatialDemoExposure
//
//      NOTE: You should NOT change this file as it may cause incorrect
//            behaviour. Any changes that you do make will be lost if
//            this code is regenerated.
//
//*****************************************************************************

namespace SpatialDemoExposure
{
	using System;
	using System.Collections.Generic;
	using System.Runtime.Serialization;
	using JadeSoftware.Joob;
	using JadeSoftware.Joob.Client;
	using JadeSoftware.Joob.Metadata;
	using JadeSoftware.Joob.Management;
	using JadeSoftware.Joob.MetaSchema;
	using JadeSoftware.Jade.DotNetInterop;


	[System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
	[JadeSoftware.Joob.Client.JoobDictionaryKeyClassAttribute(typeof(CountyByNameDict))]
	public partial class CountyByNameDictKey : JadeSoftware.Joob.JoobDictionaryKey
	{

		private static JadeSoftware.Joob.KeyMetadata _name = MetadataCache<CountyByNameDictMetadata>.GetData(null).NameKey;

		public CountyByNameDictKey() :
			base(new JadeSoftware.Joob.KeyMetadata[] {
					_name})
		{
		}

		public CountyByNameDictKey(String name) :
				this()
		{
			this.Name = name;
		}

		[JadeSoftware.Joob.Client.JoobDictionaryKeyAttribute("name", 0, typeof(String), Length = 50, CaseSensitive = true, Ascending = true, SortOrder = 0)]
		public String Name
		{
			get
			{
				return ((String)(this.Keys[0]));
			}
			set
			{
				this.Keys[0] = value;
			}
		}
	}

	[System.Runtime.Serialization.KnownTypeAttribute(typeof(County))]
	[System.Runtime.Serialization.KnownTypeAttribute(typeof(CountyByNameDictKey))]
	[System.Runtime.Serialization.CollectionDataContractAttribute(IsReference=true)]
	[System.ComponentModel.DataAnnotations.MetadataTypeAttribute(typeof(CountyByNameDictMetadata))]
	[JadeSoftware.Joob.Client.JoobClassAttribute("CountyByNameDict", "RootSchema.JoobSpatialDemoSchema", ClassNamespace = "SpatialDemoExposure", DuplicatesAllowed = true)]
	[JadeSoftware.Joob.Metadata.JomlTypeAttribute(JadeSoftware.Joob.Metadata.JomlTypeKind.ClassCollection, "CountyByNameDict", typeof(MemberKeyDictionary<CountyByNameDictKey, County>), MembershipType=typeof(County), Keys="name")]
	public partial class CountyByNameDict : MemberKeyDictionary<CountyByNameDictKey, County>
	{

		private static CountyByNameDictMetadata _metaModel;

		partial void Initialize();


		static CountyByNameDict()
		{
			_metaModel = MetadataCache<CountyByNameDictMetadata>.GetData(null);
		}

		public CountyByNameDict() : 
				this(JadeSoftware.Joob.ClassPersistence.Persistent)
		{
		}

		public CountyByNameDict(JadeSoftware.Joob.ClassPersistence lifetime) : 
				base(lifetime, typeof(CountyByNameDict), _metaModel.metaClass)
		{
			this.Initialize();
		}

		protected CountyByNameDict(JadeSoftware.Joob.ClassPersistence lifetime, System.Type type, JadeSoftware.Joob.ClassMetadata metaClass) :
		        base(lifetime, type, metaClass)
		{
		    this.Initialize();
		}

		public virtual County this[String name]
		{
			get
			{
				CountyByNameDictKey _key_ = new CountyByNameDictKey(name);
				 return base[_key_];
			}
			set
			{
				CountyByNameDictKey _key_ = new CountyByNameDictKey(name);
				base[_key_] = value;
			}
		}

		public virtual bool TryGetValue(String name, out County value)
		{
			CountyByNameDictKey _key_ = new CountyByNameDictKey(name);
			return base.TryGetValue(_key_, out value);
		}

		public virtual bool TryGetValue(String name, JadeSoftware.Joob.SearchStrategy strategy, out County value)
		{
			CountyByNameDictKey _key_ = new CountyByNameDictKey(name);
			return base.TryGetValue(_key_, strategy, out value);
		}

		public virtual IJoobDictionaryEnumerable<CountyByNameDictKey, County> StartingAtKey(String name)
		{
			CountyByNameDictKey _key_ = new CountyByNameDictKey(name);
			return base.StartingAtKey(_key_);
		}

		public virtual IJoobDictionaryEnumerable<CountyByNameDictKey, County> StartingAtKey(String name, JadeSoftware.Joob.SearchStrategy strategy)
		{
			CountyByNameDictKey _key_ = new CountyByNameDictKey(name);
			return base.StartingAtKey(_key_, strategy);
		}

		public virtual void PutAtKey(String name, County value)
		{
			CountyByNameDictKey _key_ = new CountyByNameDictKey(name);
			base.PutAtKey(_key_, value);
		}

		public virtual bool TryPutAtKey(String name, County value)
		{
			CountyByNameDictKey _key_ = new CountyByNameDictKey(name);
			return base.TryPutAtKey(_key_, value);
		}

		public virtual bool TryPutAtKeyDeferred(String name, County value)
		{
			CountyByNameDictKey _key_ = new CountyByNameDictKey(name);
			return base.TryPutAtKeyDeferred(_key_, value);
		}

		public virtual void Remove(String name)
		{
			CountyByNameDictKey _key_ = new CountyByNameDictKey(name);
			base.Remove(_key_);
		}

		public virtual void Remove(String name, County member)
		{
			CountyByNameDictKey _key_ = new CountyByNameDictKey(name);
			base.Remove(_key_, member);
		}

		public virtual County TryRemove(String name)
		{
			CountyByNameDictKey _key_ = new CountyByNameDictKey(name);
			return base.TryRemove(_key_);
		}

		public virtual bool TryRemove(String name, County member)
		{
			CountyByNameDictKey _key_ = new CountyByNameDictKey(name);
			return base.TryRemove(_key_, member);
		}

		public virtual bool TryRemoveDeferred(String name, County member)
		{
			CountyByNameDictKey _key_ = new CountyByNameDictKey(name);
			return base.TryRemoveDeferred(_key_, member);
		}

		public virtual bool ContainsKey(String name)
		{
			CountyByNameDictKey _key_ = new CountyByNameDictKey(name);
			return base.ContainsKey(_key_);
		}
	}

	[System.Runtime.Serialization.KnownTypeAttribute(typeof(County))]
	[System.Runtime.Serialization.KnownTypeAttribute(typeof(CountyByNameDictKey))]
	[System.Runtime.Serialization.CollectionDataContractAttribute(IsReference=true)]
	[System.ComponentModel.DataAnnotations.MetadataTypeAttribute(typeof(CountyByNameDictMetadata))]
	[JadeSoftware.Joob.Client.JoobClassAttribute("CountyByNameDict", "RootSchema.JoobSpatialDemoSchema", ClassNamespace="SpatialDemoExposure")]
	public abstract partial class CountyByNameDict<TKey, TValue> : MemberKeyDictionary<TKey, TValue>
		where TKey : JadeSoftware.Joob.IJoobDictionaryKey, new ()
		where TValue : County
	{

		private static CountyByNameDictMetadata _metaModel;

		partial void Initialize();


		static CountyByNameDict()
		{
			_metaModel = MetadataCache<CountyByNameDictMetadata>.GetData(null);
		}

		protected CountyByNameDict(JadeSoftware.Joob.ClassPersistence lifetime, System.Type type, JadeSoftware.Joob.ClassMetadata metaClass) :
		        base(lifetime, type, metaClass)
		{
		    this.Initialize();
		}
	}

	public partial class CountyByNameDictMetadata : JadeSoftware.Joob.IDomainMetadata
	{

		internal JadeSoftware.Joob.ClassMetadata metaClass;

		internal JadeSoftware.Joob.KeyMetadata NameKey;

		private CountyByNameDictMetadata()
		{
		}

		public CountyByNameDictMetadata(JadeSoftware.Joob.Client.JoobConnection connection)
		{
			this.InitializeProperties(connection);
		}

		private void InitializeProperties(JadeSoftware.Joob.Client.JoobConnection connection)
		{
			metaClass = new JadeSoftware.Joob.ClassMetadata(connection, typeof(CountyByNameDict), "CountyByNameDict", "RootSchema.JoobSpatialDemoSchema", JadeSoftware.Joob.DuplicationOption.Allowed);
			this.NameKey = metaClass.CheckMemberKey(typeof(CountyByNameDict), typeof(County), "name", typeof(String), 50, JadeSoftware.Joob.CaseSensitivityOption.Sensitive, JadeSoftware.Joob.KeyOrderOption.Ascending);
		}
	}
}
