//*****************************************************************************
//
//      This code was generated by the JADE Exposure Wizard.
//
//      JADE Version    : 20.0.01
//      Generation date : Tuesday, 19 January 2021
//      Generated by    : cnwta3
//      JADE Schema     : JoobSpatialDemoSchema
//      Exposure Name   : SpatialDemoExposure
//
//      NOTE: You should NOT change this file as it may cause incorrect
//            behaviour. Any changes that you do make will be lost if
//            this code is regenerated.
//
//*****************************************************************************

namespace SpatialDemoExposure
{
	using System;
	using System.Collections.Generic;
	using System.Runtime.Serialization;
	using JadeSoftware.Joob;
	using JadeSoftware.Joob.Client;
	using JadeSoftware.Joob.Metadata;
	using JadeSoftware.Joob.Management;
	using JadeSoftware.Joob.MetaSchema;
	using JadeSoftware.Jade.DotNetInterop;


	[System.Runtime.Serialization.KnownTypeAttribute(typeof(Person))]
	[System.Runtime.Serialization.CollectionDataContractAttribute(IsReference=true)]
	[System.ComponentModel.DataAnnotations.MetadataTypeAttribute(typeof(GeometriesRTreeMetadata))]
	[JadeSoftware.Joob.Client.JoobClassAttribute("GeometriesRTree", "RootSchema.JoobSpatialDemoSchema", ClassNamespace = "SpatialDemoExposure", DuplicatesAllowed = false)]
	[JadeSoftware.Joob.Metadata.JomlTypeAttribute(JadeSoftware.Joob.Metadata.JomlTypeKind.ClassCollection, "GeometriesRTree", typeof(ExtKeyRTree<JoobGeometry, Person>), MembershipType=typeof(Person), Keys="ExternalKey!:geom:JoobGeometry")]
	public partial class GeometriesRTree : ExtKeyRTree<JoobGeometry, Person>
	{

		private static GeometriesRTreeMetadata _metaModel;

		partial void Initialize();


		static GeometriesRTree()
		{
			_metaModel = MetadataCache<GeometriesRTreeMetadata>.GetData(null);
		}

		public GeometriesRTree() : 
				this(JadeSoftware.Joob.ClassPersistence.Persistent)
		{
		}

		public GeometriesRTree(JadeSoftware.Joob.ClassPersistence lifetime) : 
				base(lifetime, typeof(GeometriesRTree), _metaModel.metaClass)
		{
			this.Initialize();
		}

		protected GeometriesRTree(JadeSoftware.Joob.ClassPersistence lifetime, System.Type type, JadeSoftware.Joob.ClassMetadata metaClass) :
		        base(lifetime, type, metaClass)
		{
		    this.Initialize();
		}
	}

	public partial class GeometriesRTreeMetadata : JadeSoftware.Joob.IDomainMetadata
	{

		internal JadeSoftware.Joob.ClassMetadata metaClass;

		internal JadeSoftware.Joob.KeyMetadata GeomKey;

		private GeometriesRTreeMetadata()
		{
		}

		public GeometriesRTreeMetadata(JadeSoftware.Joob.Client.JoobConnection connection)
		{
			this.InitializeProperties(connection);
		}

		private void InitializeProperties(JadeSoftware.Joob.Client.JoobConnection connection)
		{
			metaClass = new JadeSoftware.Joob.ClassMetadata(connection, typeof(GeometriesRTree), "GeometriesRTree", "RootSchema.JoobSpatialDemoSchema", JadeSoftware.Joob.DuplicationOption.NotAllowed);
			this.GeomKey = metaClass.CheckExternalKey(typeof(GeometriesRTree), "geom", typeof(JoobGeometry), JadeSoftware.Joob.CaseSensitivityOption.Sensitive, JadeSoftware.Joob.KeyOrderOption.Ascending);
		}
	}
}
