//*****************************************************************************
//
//      This code was generated by the JADE Exposure Wizard.
//
//      JADE Version    : 20.0.01
//      Generation date : Tuesday, 19 January 2021
//      Generated by    : cnwta3
//      JADE Schema     : JoobSpatialDemoSchema
//      Exposure Name   : SpatialDemoExposure
//
//      NOTE: You should NOT change this file as it may cause incorrect
//            behaviour. Any changes that you do make will be lost if
//            this code is regenerated.
//
//*****************************************************************************

namespace SpatialDemoExposure
{
	using System;
	using System.Collections.Generic;
	using System.Runtime.Serialization;
	using JadeSoftware.Joob;
	using JadeSoftware.Joob.Client;
	using JadeSoftware.Joob.Metadata;
	using JadeSoftware.Joob.Management;
	using JadeSoftware.Joob.MetaSchema;
	using JadeSoftware.Jade.DotNetInterop;

	[System.Runtime.Serialization.KnownTypeAttribute(typeof(JoobGeometry))]
	[System.Runtime.Serialization.KnownTypeAttribute(typeof(City))]
	[System.Runtime.Serialization.KnownTypeAttribute(typeof(County))]
	[System.Runtime.Serialization.KnownTypeAttribute(typeof(Person))]
	[System.Runtime.Serialization.KnownTypeAttribute(typeof(State))]
	[System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
	[System.ComponentModel.DataAnnotations.MetadataTypeAttribute(typeof(ObjectWithSpatialInfoMetadata))]
	[JadeSoftware.Joob.Client.JoobClassAttribute("ObjectWithSpatialInfo", "RootSchema.JoobSpatialDemoSchema", ClassNamespace="SpatialDemoExposure")]
	[JadeSoftware.Joob.Metadata.JomlTypeAttribute(JadeSoftware.Joob.Metadata.JomlTypeKind.Class, "ObjectWithSpatialInfo", typeof(JoobObject))]
	public partial class ObjectWithSpatialInfo : JoobObject
	{
		private static ObjectWithSpatialInfoMetadata _metaModel;
		partial void _initialize();
		static ObjectWithSpatialInfo()
		{
			_metaModel = MetadataCache<ObjectWithSpatialInfoMetadata>.GetData(null);
		}
		public ObjectWithSpatialInfo() :
			this(JadeSoftware.Joob.ClassPersistence.Persistent)
		{
		}
		public ObjectWithSpatialInfo(JadeSoftware.Joob.ClassPersistence lifetime) :
			base(lifetime, typeof(ObjectWithSpatialInfo), _metaModel.metaClass)
		{
			this._initialize();
		}
		protected ObjectWithSpatialInfo(JadeSoftware.Joob.ClassPersistence lifetime, System.Type type, JadeSoftware.Joob.ClassMetadata metaClass, params System.Object[] parameters) :
			base(lifetime, type, metaClass, parameters)
		{
			this._initialize();
		}
	
#region Jade Properties

		[JadeSoftware.Joob.Client.JoobPropertyAttribute("geom", typeof(JoobGeometry), DatabaseTypeName="JadeGeometry")]
		[System.Runtime.Serialization.DataMemberAttribute()]
		public JoobGeometry Geom
		{
			get
			{
				return this.GetPropertyReference<JoobGeometry>(_metaModel.metaClass, _metaModel.geom);
			}
			set
			{
				this.SetPropertyReference(_metaModel.metaClass, _metaModel.geom, value, false);
			}
		}
	#endregion
	}

	public partial class ObjectWithSpatialInfoMetadata : JadeSoftware.Joob.IDomainMetadata
	{

		internal JadeSoftware.Joob.ClassMetadata metaClass;
		internal JadeSoftware.Joob.PropertyMetadata geom;

		private ObjectWithSpatialInfoMetadata()
		{
		}
		partial void InitializeDynamicProperties(JadeSoftware.Joob.Client.IJoobConnection connection);

		public ObjectWithSpatialInfoMetadata(JadeSoftware.Joob.Client.JoobConnection connection)
		{
			metaClass = new JadeSoftware.Joob.ClassMetadata(connection, typeof(ObjectWithSpatialInfo), "ObjectWithSpatialInfo", "RootSchema.JoobSpatialDemoSchema");
			this.InitializeProperties(connection);
			this.InitializeDynamicProperties(connection);
		}

		private void InitializeProperties(JadeSoftware.Joob.Client.IJoobConnection connection)
		{
			geom = metaClass.CheckProperty("geom", typeof(JoobGeometry));
		}
	}
}
