//*****************************************************************************
//
//      This code was generated by the JADE Exposure Wizard.
//
//      JADE Version    : 20.0.01
//      Generation date : Monday, 18 January 2021
//      Generated by    : cnwta3
//      JADE Schema     : JoobSpatialDemoSchema
//      Exposure Name   : SpatialDemoExposure
//
//      NOTE: You should NOT change this file as it may cause incorrect
//            behaviour. Any changes that you do make will be lost if
//            this code is regenerated.
//
//*****************************************************************************

namespace SpatialDemoExposure
{
	using System;
	using System.Collections.Generic;
	using System.Runtime.Serialization;
	using JadeSoftware.Joob;
	using JadeSoftware.Joob.Client;
	using JadeSoftware.Joob.Metadata;
	using JadeSoftware.Joob.Management;
	using JadeSoftware.Joob.MetaSchema;
	using JadeSoftware.Jade.DotNetInterop;


	[System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
	[JadeSoftware.Joob.Client.JoobDictionaryKeyClassAttribute(typeof(SpatialLayerByNameDict))]
	public partial class SpatialLayerByNameDictKey : JadeSoftware.Joob.JoobDictionaryKey
	{

		private static JadeSoftware.Joob.KeyMetadata _name = MetadataCache<SpatialLayerByNameDictMetadata>.GetData(null).NameKey;

		public SpatialLayerByNameDictKey() :
			base(new JadeSoftware.Joob.KeyMetadata[] {
					_name})
		{
		}

		public SpatialLayerByNameDictKey(String name) :
				this()
		{
			this.Name = name;
		}

		[JadeSoftware.Joob.Client.JoobDictionaryKeyAttribute("name", 0, typeof(String), Length = 50, CaseSensitive = true, Ascending = true, SortOrder = 0)]
		public String Name
		{
			get
			{
				return ((String)(this.Keys[0]));
			}
			set
			{
				this.Keys[0] = value;
			}
		}
	}

	[System.Runtime.Serialization.KnownTypeAttribute(typeof(SpatialLayer))]
	[System.Runtime.Serialization.KnownTypeAttribute(typeof(SpatialLayerByNameDictKey))]
	[System.Runtime.Serialization.CollectionDataContractAttribute(IsReference=true)]
	[System.ComponentModel.DataAnnotations.MetadataTypeAttribute(typeof(SpatialLayerByNameDictMetadata))]
	[JadeSoftware.Joob.Client.JoobClassAttribute("SpatialLayerByNameDict", "RootSchema.JoobSpatialDemoSchema", ClassNamespace = "SpatialDemoExposure", DuplicatesAllowed = false)]
	[JadeSoftware.Joob.Metadata.JomlTypeAttribute(JadeSoftware.Joob.Metadata.JomlTypeKind.ClassCollection, "SpatialLayerByNameDict", typeof(MemberKeyDictionary<SpatialLayerByNameDictKey, SpatialLayer>), MembershipType=typeof(SpatialLayer), Keys="name")]
	public partial class SpatialLayerByNameDict : MemberKeyDictionary<SpatialLayerByNameDictKey, SpatialLayer>
	{

		private static SpatialLayerByNameDictMetadata _metaModel;

		partial void Initialize();


		static SpatialLayerByNameDict()
		{
			_metaModel = MetadataCache<SpatialLayerByNameDictMetadata>.GetData(null);
		}

		public SpatialLayerByNameDict() : 
				this(JadeSoftware.Joob.ClassPersistence.Persistent)
		{
		}

		public SpatialLayerByNameDict(JadeSoftware.Joob.ClassPersistence lifetime) : 
				base(lifetime, typeof(SpatialLayerByNameDict), _metaModel.metaClass)
		{
			this.Initialize();
		}

		protected SpatialLayerByNameDict(JadeSoftware.Joob.ClassPersistence lifetime, System.Type type, JadeSoftware.Joob.ClassMetadata metaClass) :
		        base(lifetime, type, metaClass)
		{
		    this.Initialize();
		}

		public virtual SpatialLayer this[String name]
		{
			get
			{
				SpatialLayerByNameDictKey _key_ = new SpatialLayerByNameDictKey(name);
				 return base[_key_];
			}
			set
			{
				SpatialLayerByNameDictKey _key_ = new SpatialLayerByNameDictKey(name);
				base[_key_] = value;
			}
		}

		public virtual bool TryGetValue(String name, out SpatialLayer value)
		{
			SpatialLayerByNameDictKey _key_ = new SpatialLayerByNameDictKey(name);
			return base.TryGetValue(_key_, out value);
		}

		public virtual bool TryGetValue(String name, JadeSoftware.Joob.SearchStrategy strategy, out SpatialLayer value)
		{
			SpatialLayerByNameDictKey _key_ = new SpatialLayerByNameDictKey(name);
			return base.TryGetValue(_key_, strategy, out value);
		}

		public virtual IJoobDictionaryEnumerable<SpatialLayerByNameDictKey, SpatialLayer> StartingAtKey(String name)
		{
			SpatialLayerByNameDictKey _key_ = new SpatialLayerByNameDictKey(name);
			return base.StartingAtKey(_key_);
		}

		public virtual IJoobDictionaryEnumerable<SpatialLayerByNameDictKey, SpatialLayer> StartingAtKey(String name, JadeSoftware.Joob.SearchStrategy strategy)
		{
			SpatialLayerByNameDictKey _key_ = new SpatialLayerByNameDictKey(name);
			return base.StartingAtKey(_key_, strategy);
		}

		public virtual void PutAtKey(String name, SpatialLayer value)
		{
			SpatialLayerByNameDictKey _key_ = new SpatialLayerByNameDictKey(name);
			base.PutAtKey(_key_, value);
		}

		public virtual bool TryPutAtKey(String name, SpatialLayer value)
		{
			SpatialLayerByNameDictKey _key_ = new SpatialLayerByNameDictKey(name);
			return base.TryPutAtKey(_key_, value);
		}

		public virtual bool TryPutAtKeyDeferred(String name, SpatialLayer value)
		{
			SpatialLayerByNameDictKey _key_ = new SpatialLayerByNameDictKey(name);
			return base.TryPutAtKeyDeferred(_key_, value);
		}

		public virtual void Remove(String name)
		{
			SpatialLayerByNameDictKey _key_ = new SpatialLayerByNameDictKey(name);
			base.Remove(_key_);
		}

		public virtual void Remove(String name, SpatialLayer member)
		{
			SpatialLayerByNameDictKey _key_ = new SpatialLayerByNameDictKey(name);
			base.Remove(_key_, member);
		}

		public virtual SpatialLayer TryRemove(String name)
		{
			SpatialLayerByNameDictKey _key_ = new SpatialLayerByNameDictKey(name);
			return base.TryRemove(_key_);
		}

		public virtual bool TryRemove(String name, SpatialLayer member)
		{
			SpatialLayerByNameDictKey _key_ = new SpatialLayerByNameDictKey(name);
			return base.TryRemove(_key_, member);
		}

		public virtual bool TryRemoveDeferred(String name, SpatialLayer member)
		{
			SpatialLayerByNameDictKey _key_ = new SpatialLayerByNameDictKey(name);
			return base.TryRemoveDeferred(_key_, member);
		}

		public virtual bool ContainsKey(String name)
		{
			SpatialLayerByNameDictKey _key_ = new SpatialLayerByNameDictKey(name);
			return base.ContainsKey(_key_);
		}
	}

	[System.Runtime.Serialization.KnownTypeAttribute(typeof(SpatialLayer))]
	[System.Runtime.Serialization.KnownTypeAttribute(typeof(SpatialLayerByNameDictKey))]
	[System.Runtime.Serialization.CollectionDataContractAttribute(IsReference=true)]
	[System.ComponentModel.DataAnnotations.MetadataTypeAttribute(typeof(SpatialLayerByNameDictMetadata))]
	[JadeSoftware.Joob.Client.JoobClassAttribute("SpatialLayerByNameDict", "RootSchema.JoobSpatialDemoSchema", ClassNamespace="SpatialDemoExposure")]
	public abstract partial class SpatialLayerByNameDict<TKey, TValue> : MemberKeyDictionary<TKey, TValue>
		where TKey : JadeSoftware.Joob.IJoobDictionaryKey, new ()
		where TValue : SpatialLayer
	{

		private static SpatialLayerByNameDictMetadata _metaModel;

		partial void Initialize();


		static SpatialLayerByNameDict()
		{
			_metaModel = MetadataCache<SpatialLayerByNameDictMetadata>.GetData(null);
		}

		protected SpatialLayerByNameDict(JadeSoftware.Joob.ClassPersistence lifetime, System.Type type, JadeSoftware.Joob.ClassMetadata metaClass) :
		        base(lifetime, type, metaClass)
		{
		    this.Initialize();
		}
	}

	public partial class SpatialLayerByNameDictMetadata : JadeSoftware.Joob.IDomainMetadata
	{

		internal JadeSoftware.Joob.ClassMetadata metaClass;

		internal JadeSoftware.Joob.KeyMetadata NameKey;

		private SpatialLayerByNameDictMetadata()
		{
		}

		public SpatialLayerByNameDictMetadata(JadeSoftware.Joob.Client.JoobConnection connection)
		{
			this.InitializeProperties(connection);
		}

		private void InitializeProperties(JadeSoftware.Joob.Client.JoobConnection connection)
		{
			metaClass = new JadeSoftware.Joob.ClassMetadata(connection, typeof(SpatialLayerByNameDict), "SpatialLayerByNameDict", "RootSchema.JoobSpatialDemoSchema", JadeSoftware.Joob.DuplicationOption.NotAllowed);
			this.NameKey = metaClass.CheckMemberKey(typeof(SpatialLayerByNameDict), typeof(SpatialLayer), "name", typeof(String), 50, JadeSoftware.Joob.CaseSensitivityOption.Sensitive, JadeSoftware.Joob.KeyOrderOption.Ascending);
		}
	}
}
