//*****************************************************************************
//
//      This code was generated by the JADE Exposure Wizard.
//
//      JADE Version    : 20.0.01
//      Generation date : Tuesday, 19 January 2021
//      Generated by    : cnwta3
//      JADE Schema     : JoobSpatialDemoSchema
//      Exposure Name   : SpatialDemoExposure
//
//      NOTE: You should NOT change this file as it may cause incorrect
//            behaviour. Any changes that you do make will be lost if
//            this code is regenerated.
//
//*****************************************************************************

namespace SpatialDemoExposure
{
	using System;
	using System.Collections.Generic;
	using System.Runtime.Serialization;
	using JadeSoftware.Joob;
	using JadeSoftware.Joob.Client;
	using JadeSoftware.Joob.Metadata;
	using JadeSoftware.Joob.Management;
	using JadeSoftware.Joob.MetaSchema;
	using JadeSoftware.Jade.DotNetInterop;

	[System.Runtime.Serialization.KnownTypeAttribute(typeof(SpatialRTree))]
	[System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
	[System.ComponentModel.DataAnnotations.MetadataTypeAttribute(typeof(SpatialLayerMetadata))]
	[JadeSoftware.Joob.Client.JoobClassAttribute("SpatialLayer", "RootSchema.JoobSpatialDemoSchema", ClassNamespace="SpatialDemoExposure")]
	[JadeSoftware.Joob.Metadata.JomlTypeAttribute(JadeSoftware.Joob.Metadata.JomlTypeKind.Class, "SpatialLayer", typeof(JoobObject))]
	public partial class SpatialLayer : JoobObject
	{
		private static SpatialLayerMetadata _metaModel;
		partial void _initialize();
		static SpatialLayer()
		{
			_metaModel = MetadataCache<SpatialLayerMetadata>.GetData(null);
		}
		public SpatialLayer() :
			this(JadeSoftware.Joob.ClassPersistence.Persistent)
		{
		}
		public SpatialLayer(JadeSoftware.Joob.ClassPersistence lifetime) :
			base(lifetime, typeof(SpatialLayer), _metaModel.metaClass)
		{
			this._initialize();
		}
		protected SpatialLayer(JadeSoftware.Joob.ClassPersistence lifetime, System.Type type, JadeSoftware.Joob.ClassMetadata metaClass, params System.Object[] parameters) :
			base(lifetime, type, metaClass, parameters)
		{
			this._initialize();
		}
	
#region Jade Properties

		[JadeSoftware.Joob.Client.JoobPropertyAttribute("geometries", typeof(SpatialRTree), DatabaseTypeName="JadeSpatialRTree")]
		[System.Runtime.Serialization.DataMemberAttribute()]
		public SpatialRTree Geometries
		{
			get
			{
				return this.GetPropertyReference<SpatialRTree>(_metaModel.metaClass, _metaModel.geometries);
			}
			private set { }
		}

		[JadeSoftware.Joob.Client.JoobPropertyAttribute("name", typeof(String), Length=50, DatabaseTypeName="String")]
		[System.Runtime.Serialization.DataMemberAttribute()]
		public String Name
		{
			get
			{
				return this.GetPropertyString(_metaModel.metaClass, _metaModel.name);
			}
			set
			{
				this.SetPropertyString(_metaModel.metaClass, _metaModel.name, value);
			}
		}
	#endregion
	}

	public partial class SpatialLayerMetadata : JadeSoftware.Joob.IDomainMetadata
	{

		internal JadeSoftware.Joob.ClassMetadata metaClass;
		internal JadeSoftware.Joob.PropertyMetadata geometries;
		internal JadeSoftware.Joob.PropertyMetadata name;

		private SpatialLayerMetadata()
		{
		}
		partial void InitializeDynamicProperties(JadeSoftware.Joob.Client.IJoobConnection connection);

		public SpatialLayerMetadata(JadeSoftware.Joob.Client.JoobConnection connection)
		{
			metaClass = new JadeSoftware.Joob.ClassMetadata(connection, typeof(SpatialLayer), "SpatialLayer", "RootSchema.JoobSpatialDemoSchema");
			this.InitializeProperties(connection);
			this.InitializeDynamicProperties(connection);
		}

		private void InitializeProperties(JadeSoftware.Joob.Client.IJoobConnection connection)
		{
			geometries = metaClass.CheckProperty("geometries", typeof(SpatialRTree));
			name = metaClass.CheckProperty("name", typeof(String), 50);
		}
	}
}
