//*****************************************************************************
//
//      This code was generated by the JADE Exposure Wizard.
//
//      JADE Version    : 20.0.01
//      Generation date : Monday, 18 January 2021
//      Generated by    : cnwta3
//      JADE Schema     : JoobSpatialDemoSchema
//      Exposure Name   : SpatialDemoExposure
//
//      NOTE: You should NOT change this file as it may cause incorrect
//            behaviour. Any changes that you do make will be lost if
//            this code is regenerated.
//
//*****************************************************************************

namespace SpatialDemoExposure
{
	using System;
	using System.Collections.Generic;
	using System.Runtime.Serialization;
	using JadeSoftware.Joob;
	using JadeSoftware.Joob.Client;
	using JadeSoftware.Joob.Metadata;
	using JadeSoftware.Joob.Management;
	using JadeSoftware.Joob.MetaSchema;
	using JadeSoftware.Jade.DotNetInterop;


	[System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
	[JadeSoftware.Joob.Client.JoobDictionaryKeyClassAttribute(typeof(StateByAbbrDict))]
	public partial class StateByAbbrDictKey : JadeSoftware.Joob.JoobDictionaryKey
	{

		private static JadeSoftware.Joob.KeyMetadata _abbr = MetadataCache<StateByAbbrDictMetadata>.GetData(null).AbbrKey;

		public StateByAbbrDictKey() :
			base(new JadeSoftware.Joob.KeyMetadata[] {
					_abbr})
		{
		}

		public StateByAbbrDictKey(String abbr) :
				this()
		{
			this.Abbr = abbr;
		}

		[JadeSoftware.Joob.Client.JoobDictionaryKeyAttribute("abbr", 0, typeof(String), Length = 2, CaseSensitive = true, Ascending = true, SortOrder = 0)]
		public String Abbr
		{
			get
			{
				return ((String)(this.Keys[0]));
			}
			set
			{
				this.Keys[0] = value;
			}
		}
	}

	[System.Runtime.Serialization.KnownTypeAttribute(typeof(State))]
	[System.Runtime.Serialization.KnownTypeAttribute(typeof(StateByAbbrDictKey))]
	[System.Runtime.Serialization.CollectionDataContractAttribute(IsReference=true)]
	[System.ComponentModel.DataAnnotations.MetadataTypeAttribute(typeof(StateByAbbrDictMetadata))]
	[JadeSoftware.Joob.Client.JoobClassAttribute("StateByAbbrDict", "RootSchema.JoobSpatialDemoSchema", ClassNamespace = "SpatialDemoExposure", DuplicatesAllowed = false)]
	[JadeSoftware.Joob.Metadata.JomlTypeAttribute(JadeSoftware.Joob.Metadata.JomlTypeKind.ClassCollection, "StateByAbbrDict", typeof(MemberKeyDictionary<StateByAbbrDictKey, State>), MembershipType=typeof(State), Keys="abbr")]
	public partial class StateByAbbrDict : MemberKeyDictionary<StateByAbbrDictKey, State>
	{

		private static StateByAbbrDictMetadata _metaModel;

		partial void Initialize();


		static StateByAbbrDict()
		{
			_metaModel = MetadataCache<StateByAbbrDictMetadata>.GetData(null);
		}

		public StateByAbbrDict() : 
				this(JadeSoftware.Joob.ClassPersistence.Persistent)
		{
		}

		public StateByAbbrDict(JadeSoftware.Joob.ClassPersistence lifetime) : 
				base(lifetime, typeof(StateByAbbrDict), _metaModel.metaClass)
		{
			this.Initialize();
		}

		protected StateByAbbrDict(JadeSoftware.Joob.ClassPersistence lifetime, System.Type type, JadeSoftware.Joob.ClassMetadata metaClass) :
		        base(lifetime, type, metaClass)
		{
		    this.Initialize();
		}

		public virtual State this[String abbr]
		{
			get
			{
				StateByAbbrDictKey _key_ = new StateByAbbrDictKey(abbr);
				 return base[_key_];
			}
			set
			{
				StateByAbbrDictKey _key_ = new StateByAbbrDictKey(abbr);
				base[_key_] = value;
			}
		}

		public virtual bool TryGetValue(String abbr, out State value)
		{
			StateByAbbrDictKey _key_ = new StateByAbbrDictKey(abbr);
			return base.TryGetValue(_key_, out value);
		}

		public virtual bool TryGetValue(String abbr, JadeSoftware.Joob.SearchStrategy strategy, out State value)
		{
			StateByAbbrDictKey _key_ = new StateByAbbrDictKey(abbr);
			return base.TryGetValue(_key_, strategy, out value);
		}

		public virtual IJoobDictionaryEnumerable<StateByAbbrDictKey, State> StartingAtKey(String abbr)
		{
			StateByAbbrDictKey _key_ = new StateByAbbrDictKey(abbr);
			return base.StartingAtKey(_key_);
		}

		public virtual IJoobDictionaryEnumerable<StateByAbbrDictKey, State> StartingAtKey(String abbr, JadeSoftware.Joob.SearchStrategy strategy)
		{
			StateByAbbrDictKey _key_ = new StateByAbbrDictKey(abbr);
			return base.StartingAtKey(_key_, strategy);
		}

		public virtual void PutAtKey(String abbr, State value)
		{
			StateByAbbrDictKey _key_ = new StateByAbbrDictKey(abbr);
			base.PutAtKey(_key_, value);
		}

		public virtual bool TryPutAtKey(String abbr, State value)
		{
			StateByAbbrDictKey _key_ = new StateByAbbrDictKey(abbr);
			return base.TryPutAtKey(_key_, value);
		}

		public virtual bool TryPutAtKeyDeferred(String abbr, State value)
		{
			StateByAbbrDictKey _key_ = new StateByAbbrDictKey(abbr);
			return base.TryPutAtKeyDeferred(_key_, value);
		}

		public virtual void Remove(String abbr)
		{
			StateByAbbrDictKey _key_ = new StateByAbbrDictKey(abbr);
			base.Remove(_key_);
		}

		public virtual void Remove(String abbr, State member)
		{
			StateByAbbrDictKey _key_ = new StateByAbbrDictKey(abbr);
			base.Remove(_key_, member);
		}

		public virtual State TryRemove(String abbr)
		{
			StateByAbbrDictKey _key_ = new StateByAbbrDictKey(abbr);
			return base.TryRemove(_key_);
		}

		public virtual bool TryRemove(String abbr, State member)
		{
			StateByAbbrDictKey _key_ = new StateByAbbrDictKey(abbr);
			return base.TryRemove(_key_, member);
		}

		public virtual bool TryRemoveDeferred(String abbr, State member)
		{
			StateByAbbrDictKey _key_ = new StateByAbbrDictKey(abbr);
			return base.TryRemoveDeferred(_key_, member);
		}

		public virtual bool ContainsKey(String abbr)
		{
			StateByAbbrDictKey _key_ = new StateByAbbrDictKey(abbr);
			return base.ContainsKey(_key_);
		}
	}

	[System.Runtime.Serialization.KnownTypeAttribute(typeof(State))]
	[System.Runtime.Serialization.KnownTypeAttribute(typeof(StateByAbbrDictKey))]
	[System.Runtime.Serialization.CollectionDataContractAttribute(IsReference=true)]
	[System.ComponentModel.DataAnnotations.MetadataTypeAttribute(typeof(StateByAbbrDictMetadata))]
	[JadeSoftware.Joob.Client.JoobClassAttribute("StateByAbbrDict", "RootSchema.JoobSpatialDemoSchema", ClassNamespace="SpatialDemoExposure")]
	public abstract partial class StateByAbbrDict<TKey, TValue> : MemberKeyDictionary<TKey, TValue>
		where TKey : JadeSoftware.Joob.IJoobDictionaryKey, new ()
		where TValue : State
	{

		private static StateByAbbrDictMetadata _metaModel;

		partial void Initialize();


		static StateByAbbrDict()
		{
			_metaModel = MetadataCache<StateByAbbrDictMetadata>.GetData(null);
		}

		protected StateByAbbrDict(JadeSoftware.Joob.ClassPersistence lifetime, System.Type type, JadeSoftware.Joob.ClassMetadata metaClass) :
		        base(lifetime, type, metaClass)
		{
		    this.Initialize();
		}
	}

	public partial class StateByAbbrDictMetadata : JadeSoftware.Joob.IDomainMetadata
	{

		internal JadeSoftware.Joob.ClassMetadata metaClass;

		internal JadeSoftware.Joob.KeyMetadata AbbrKey;

		private StateByAbbrDictMetadata()
		{
		}

		public StateByAbbrDictMetadata(JadeSoftware.Joob.Client.JoobConnection connection)
		{
			this.InitializeProperties(connection);
		}

		private void InitializeProperties(JadeSoftware.Joob.Client.JoobConnection connection)
		{
			metaClass = new JadeSoftware.Joob.ClassMetadata(connection, typeof(StateByAbbrDict), "StateByAbbrDict", "RootSchema.JoobSpatialDemoSchema", JadeSoftware.Joob.DuplicationOption.NotAllowed);
			this.AbbrKey = metaClass.CheckMemberKey(typeof(StateByAbbrDict), typeof(State), "abbr", typeof(String), 2, JadeSoftware.Joob.CaseSensitivityOption.Sensitive, JadeSoftware.Joob.KeyOrderOption.Ascending);
		}
	}
}
