//*****************************************************************************
//
//      This code was generated by the JADE Exposure Wizard.
//
//      JADE Version    : 20.0.01
//      Generation date : Tuesday, 19 January 2021
//      Generated by    : cnwta3
//      JADE Schema     : JoobSpatialDemoSchema
//      Exposure Name   : SpatialDemoExposure
//
//      NOTE: You should NOT change this file as it may cause incorrect
//            behaviour. Any changes that you do make will be lost if
//            this code is regenerated.
//
//*****************************************************************************

namespace SpatialDemoExposure
{
	using System;
	using System.Collections.Generic;
	using System.Runtime.Serialization;
	using JadeSoftware.Joob;
	using JadeSoftware.Joob.Client;
	using JadeSoftware.Joob.Metadata;
	using JadeSoftware.Joob.Management;
	using JadeSoftware.Joob.MetaSchema;
	using JadeSoftware.Jade.DotNetInterop;


	[System.Runtime.Serialization.KnownTypeAttribute(typeof(JoobGeometry))]
	[System.Runtime.Serialization.KnownTypeAttribute(typeof(State))]
	[System.Runtime.Serialization.CollectionDataContractAttribute(IsReference=true)]
	[System.ComponentModel.DataAnnotations.MetadataTypeAttribute(typeof(StateByGeomRTreeMetadata))]
	[JadeSoftware.Joob.Client.JoobClassAttribute("StateByGeomRTree", "RootSchema.JoobSpatialDemoSchema", ClassNamespace = "SpatialDemoExposure", DuplicatesAllowed = false)]
	[JadeSoftware.Joob.Metadata.JomlTypeAttribute(JadeSoftware.Joob.Metadata.JomlTypeKind.ClassCollection, "StateByGeomRTree", typeof(MemberKeyRTree<JoobGeometry, State>), MembershipType=typeof(State), Keys="geom")]
	public partial class StateByGeomRTree : MemberKeyRTree<JoobGeometry, State>
	{

		private static StateByGeomRTreeMetadata _metaModel;

		partial void Initialize();


		static StateByGeomRTree()
		{
			_metaModel = MetadataCache<StateByGeomRTreeMetadata>.GetData(null);
		}

		public StateByGeomRTree() : 
				this(JadeSoftware.Joob.ClassPersistence.Persistent)
		{
		}

		public StateByGeomRTree(JadeSoftware.Joob.ClassPersistence lifetime) : 
				base(lifetime, typeof(StateByGeomRTree), _metaModel.metaClass)
		{
			this.Initialize();
		}

		protected StateByGeomRTree(JadeSoftware.Joob.ClassPersistence lifetime, System.Type type, JadeSoftware.Joob.ClassMetadata metaClass) :
		        base(lifetime, type, metaClass)
		{
		    this.Initialize();
		}
	}

	public partial class StateByGeomRTreeMetadata : JadeSoftware.Joob.IDomainMetadata
	{

		internal JadeSoftware.Joob.ClassMetadata metaClass;

		internal JadeSoftware.Joob.KeyMetadata GeomKey;

		private StateByGeomRTreeMetadata()
		{
		}

		public StateByGeomRTreeMetadata(JadeSoftware.Joob.Client.JoobConnection connection)
		{
			this.InitializeProperties(connection);
		}

		private void InitializeProperties(JadeSoftware.Joob.Client.JoobConnection connection)
		{
			MetadataCache<JoobGeometryMetadata>.LoadData(null);
			metaClass = new JadeSoftware.Joob.ClassMetadata(connection, typeof(StateByGeomRTree), "StateByGeomRTree", "RootSchema.JoobSpatialDemoSchema", JadeSoftware.Joob.DuplicationOption.NotAllowed);
			this.GeomKey = metaClass.CheckMemberKey(typeof(StateByGeomRTree), typeof(State), "geom", typeof(JoobGeometry), JadeSoftware.Joob.CaseSensitivityOption.Sensitive, JadeSoftware.Joob.KeyOrderOption.Ascending);
		}
	}
}
